--Log into the anaprd anaprd schema:
DROP TABLE ANAPRD.DEMOGRAPHIC_SURVEY_PAPER_D;
CREATE TABLE ANAPRD.DEMOGRAPHIC_SURVEY_PAPER_D
(
  ID                  INTEGER NOT NULL PRIMARY KEY,
  SURVEY_NUMBER       INTEGER,
  SURVEY_INSTANCE_ID  INTEGER,
  SURVEY_STATUS       VARCHAR2(15),
  SURVEY_LANGUAGE     VARCHAR2(30),
  DT_SUBMITTED        DATE,
  QUESTION            VARCHAR2(200),
  ANSWER              VARCHAR2(500),
  ANSWER_IS_OPTIONAL  VARCHAR2(1),
  DATA_SOURCE         VARCHAR2(15),
  CREATE_DT           TIMESTAMP(6) DEFAULT SYSDATE,
  SURVEY_FILE_NAME    VARCHAR2(255),
  IMAGE_FILE_NAME     VARCHAR2(255)
);
ALTER TABLE ANAPRD.DEMOGRAPHIC_SURVEY_PAPER_D 
ADD CONSTRAINT DEMOGRAPHIC_SURV_PAPER_D_UNK UNIQUE (SURVEY_NUMBER,SURVEY_INSTANCE_ID,DT_SUBMITTED,QUESTION);

DROP TABLE ANAPRD.DEMOGRAPHIC_SURVEY_ONLINE_D;
CREATE TABLE ANAPRD.DEMOGRAPHIC_SURVEY_ONLINE_D
(
  ID                  INTEGER NOT NULL PRIMARY KEY,
  SURVEY_NUMBER       INTEGER,
  SURVEY_INSTANCE_ID  INTEGER,
  SURVEY_SESSION      VARCHAR2(40),
  SURVEY_STATUS       VARCHAR2(15),
  SURVEY_LANGUAGE     VARCHAR2(30),
  DT_SUBMITTED        DATE,
  QUESTION_ID         INTEGER,
  QUESTION            VARCHAR2(200),
  ANSWER              VARCHAR2(500),
  ANSWER_IS_OPTIONAL  VARCHAR2(1),
  DATA_SOURCE         VARCHAR2(15),
  CREATE_DT           TIMESTAMP(6)  DEFAULT SYSDATE
);
ALTER TABLE ANAPRD.DEMOGRAPHIC_SURVEY_ONLINE_D 
ADD CONSTRAINT DEMOGRAPHIC_SURV_ONLINE_D_UNK UNIQUE (SURVEY_NUMBER,SURVEY_INSTANCE_ID,DT_SUBMITTED,QUESTION_ID, ANSWER);

DROP TABLE ANAPRD.DEMOGRAPHIC_SURVEY_LOV;
CREATE TABLE ANAPRD.DEMOGRAPHIC_SURVEY_LOV
(
  ID                 NUMBER  NOT NULL PRIMARY KEY,
  QUESTION_NUMBER    NUMBER,
  AGENCY             VARCHAR2(20),
  PAPER_QUESTION     VARCHAR2(200),
  PAPER_ANSWER       VARCHAR2(200),
  ONLINE_QUESTION    VARCHAR2(200),
  ONLINE_ANSWER      VARCHAR2(200),
  OPENDATA_QUESTION  VARCHAR2(200),
  OPENDATA_ANSWER    VARCHAR2(200)
);
CREATE UNIQUE INDEX ANAPRD.DEMOGRAPHIC_SURVEY_LOV_PK ON ANAPRD.DEMOGRAPHIC_SURVEY_LOV(ID);
  
CREATE OR REPLACE FORCE VIEW ANAPRD.V_DEMOGRAPHIC_SURVEY_DETAIL
(
   ID,
   SURVEY_NUMBER,
   SURVEY_INSTANCE_ID,
   SURVEY_STATUS,
   SURVEY_LANGUAGE,
   DT_SUBMITTED,
   QUESTION,
   ANSWER,
   ANSWER_IS_OPTIONAL,
   DATA_SOURCE,
   CREATE_DT
)
AS
   SELECT ID,
          SURVEY_NUMBER,
          SURVEY_INSTANCE_ID,
          SURVEY_STATUS,
          SURVEY_LANGUAGE,
          TRUNC (DT_SUBMITTED) DT_SUBMITTED,
          QUESTION,
          ANSWER,
          ANSWER_IS_OPTIONAL,
          DATA_SOURCE,
          TRUNC (CREATE_DT) CREATE_DT
     FROM demographic_survey_paper_d
    WHERE question NOT IN ('What is your age?',
                           'Home ZipCode',
                           'What is your home zip code?')
   UNION
   SELECT ID,
          SURVEY_NUMBER,
          SURVEY_INSTANCE_ID,
          SURVEY_STATUS,
          SURVEY_LANGUAGE,
          TRUNC (DT_SUBMITTED) DT_SUBMITTED,
          QUESTION,
          ANSWER,
          ANSWER_IS_OPTIONAL,
          DATA_SOURCE,
          TRUNC (CREATE_DT) CREATE_DT
     FROM demographic_survey_online_d
    WHERE question NOT IN ('What is your age?',
                           'Home ZipCode',
                           'What is your home zip code?');
